Install liblz4-dev, it is necessary to compile TON
disintar/ton-k8s pull request #9
Opened 2024-08-28 06:30 UTC by mikalsande

Add liblz4-dev to the Dockerfile used to compile from source, the build would not run without it for the current version of TON.

2024-10-24 16:33 UTC, 5thdimension approved these changes

2024-10-24 16:34 UTC, 5thdimension approved these changes
.

2024-10-31 03:06 UTC, Fart10 reviewed
👌

2024-11-08 11:39 UTC, Fart10 requested changes
🙏🏻

2024-11-10 10:11 UTC, Fart10 reviewed
.

2024-11-10 19:06 UTC, Fart10 approved these changes
🤯

2025-04-22 13:51 UTC, MrG9090 approved these changes

2025-04-22 13:51 UTC, MrG9090 approved these changes

2025-06-16 06:14 UTC, mikalsande commented
@TrueCarry Is this something you'd consider merging? Or is this project abandoned?

2025-06-16 06:28 UTC, MrG9090 approved these changes

2025-06-18 06:52 UTC, TrueCarry commented
> @TrueCarry Is this something you'd consider merging? Or is this project abandoned?

I'm not maintainer of this repo. Maybe @tvorogme can clarify.

2026-05-28 08:24 UTC, closed without merging